#!/usr/bin/env python3
"""Render a single self-contained static HTML dashboard from the register.

Read-only: no similarity/ML, just the shared-theme/taxonomy/standards-gap/
explicit-link signals already in the schema. Meant to be regenerated by a
scheduled GitHub Action and published to GitHub Pages — see
docs/dashboard.md.

Usage: python scripts/generate_dashboard.py --out dashboard/index.html
"""

import argparse
import html
import sqlite3
import sys
from pathlib import Path

from _env import db_path

CSS = """
body { font-family: system-ui, sans-serif; margin: 2rem; color: #1a1a1a; background: #fff; }
h1 { margin-bottom: 0.25rem; }
.subtitle { color: #666; margin-top: 0; }
.cards { display: flex; flex-wrap: wrap; gap: 1rem; margin: 1.5rem 0; }
.card { border: 1px solid #ddd; border-radius: 8px; padding: 1rem 1.5rem; min-width: 160px; }
.card .value { font-size: 2rem; font-weight: 700; }
.card .label { color: #666; font-size: 0.85rem; }
table { border-collapse: collapse; width: 100%; margin-bottom: 2rem; }
th, td { text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid #eee; font-size: 0.9rem; }
th { background: #fafafa; }
section h2 { border-top: 2px solid #eee; padding-top: 1.5rem; }
.empty { color: #888; font-style: italic; }
a { color: #0655c4; }
"""


def esc(value):
    return html.escape(str(value)) if value is not None else ""


def fetch_use_cases(conn):
    return conn.execute(
        """SELECT github_issue_number, title, github_issue_url, review_status, priority
           FROM use_cases ORDER BY github_issue_number"""
    ).fetchall()


def fetch_by_status(conn, status):
    return conn.execute(
        """SELECT github_issue_number, title FROM use_cases
           WHERE review_status = ? ORDER BY github_issue_number""",
        (status,),
    ).fetchall()


def fetch_unmapped(conn):
    return conn.execute(
        """SELECT uc.github_issue_number, uc.title FROM use_cases uc
           WHERE uc.id NOT IN (SELECT use_case_id FROM use_case_theme_links)
             AND uc.id NOT IN (SELECT use_case_id FROM use_case_working_group_links)
           ORDER BY uc.github_issue_number"""
    ).fetchall()


def fetch_grouped(conn, group_table, group_name_col, group_id_col, link_table, link_col):
    rows = conn.execute(
        f"""SELECT g.{group_name_col}, uc.github_issue_number, uc.title
            FROM {group_table} g
            JOIN {link_table} l ON l.{group_id_col} = g.id
            JOIN use_cases uc ON uc.id = l.{link_col}
            ORDER BY g.{group_name_col}, uc.github_issue_number"""
    ).fetchall()
    grouped = {}
    for name, issue_number, title in rows:
        grouped.setdefault(name, []).append((issue_number, title))
    return grouped


def fetch_candidate_taxonomy_terms(conn):
    return conn.execute(
        "SELECT term, definition FROM taxonomy_terms WHERE status = 'candidate' ORDER BY term"
    ).fetchall()


def fetch_explicit_related(conn):
    return conn.execute(
        """SELECT a.github_issue_number, a.title, b.github_issue_number, b.title
           FROM related_use_case_links l
           JOIN use_cases a ON a.id = l.use_case_id_a
           JOIN use_cases b ON b.id = l.use_case_id_b"""
    ).fetchall()


def render_cards(conn):
    total = conn.execute("SELECT COUNT(*) FROM use_cases").fetchone()[0]
    unreviewed = conn.execute("SELECT COUNT(*) FROM use_cases WHERE review_status = 'new'").fetchone()[0]
    mapped = conn.execute("SELECT COUNT(*) FROM use_cases WHERE review_status = 'mapped'").fetchone()[0]
    themes_supported = conn.execute(
        "SELECT COUNT(DISTINCT theme_id) FROM use_case_theme_links"
    ).fetchone()[0]
    gaps = conn.execute("SELECT COUNT(*) FROM standards_gaps").fetchone()[0]

    cards = [
        ("Total use cases", total),
        ("Unreviewed", unreviewed),
        ("Mapped", mapped),
        ("Themes with support", themes_supported),
        ("Standards gaps identified", gaps),
    ]
    items = "".join(
        f'<div class="card"><div class="value">{value}</div><div class="label">{esc(label)}</div></div>'
        for label, value in cards
    )
    return f'<div class="cards">{items}</div>'


def render_use_case_table(rows, columns=("Issue", "Title")):
    if not rows:
        return '<p class="empty">None.</p>'
    header = "".join(f"<th>{esc(c)}</th>" for c in columns)
    body_rows = []
    for row in rows:
        issue_number, title = row[0], row[1]
        rest = row[2:]
        link_cell = f'<td><a href="https://github.com/FG-TIDA/use-cases/issues/{issue_number}">#{issue_number}</a></td>'
        rest_cells = "".join(f"<td>{esc(v)}</td>" for v in rest)
        body_rows.append(f"<tr>{link_cell}<td>{esc(title)}</td>{rest_cells}</tr>")
    return f"<table><tr>{header}</tr>{''.join(body_rows)}</table>"


def render_full_table(rows):
    if not rows:
        return '<p class="empty">None.</p>'
    header = "<tr><th>Issue</th><th>Title</th><th>Status</th><th>Priority</th></tr>"
    body_rows = []
    for issue_number, title, url, status, priority in rows:
        body_rows.append(
            f'<tr><td><a href="{esc(url)}">#{issue_number}</a></td>'
            f"<td>{esc(title)}</td><td>{esc(status)}</td><td>{esc(priority)}</td></tr>"
        )
    return f"<table>{header}{''.join(body_rows)}</table>"


def render_grouped(grouped):
    if not grouped:
        return '<p class="empty">None.</p>'
    sections = []
    for name, use_cases in grouped.items():
        items = "".join(
            f'<li><a href="https://github.com/FG-TIDA/use-cases/issues/{n}">#{n}</a> {esc(t)}</li>'
            for n, t in use_cases
        )
        sections.append(f"<h3>{esc(name)} ({len(use_cases)})</h3><ul>{items}</ul>")
    return "".join(sections)


def render_related(conn):
    parts = []

    explicit = fetch_explicit_related(conn)
    if explicit:
        items = "".join(
            f"<li>#{a_num} {esc(a_title)} ↔ #{b_num} {esc(b_title)}</li>"
            for a_num, a_title, b_num, b_title in explicit
        )
        parts.append(f"<h3>Explicitly linked by a reviewer</h3><ul>{items}</ul>")

    for label, group_table, name_col, id_col, link_table, link_col in (
        ("Sharing a theme", "themes", "name", "theme_id", "use_case_theme_links", "use_case_id"),
        ("Sharing a taxonomy term", "taxonomy_terms", "term", "taxonomy_term_id", "use_case_taxonomy_links", "use_case_id"),
        ("Sharing a standards gap", "standards_gaps", "title", "standards_gap_id", "use_case_standards_gap_links", "use_case_id"),
    ):
        grouped = {
            name: uses for name, uses in fetch_grouped(conn, group_table, name_col, id_col, link_table, link_col).items()
            if len(uses) > 1
        }
        if grouped:
            parts.append(f"<h3>{label}</h3>{render_grouped(grouped)}")

    return "".join(parts) if parts else '<p class="empty">No related use cases yet.</p>'


def build_html(conn):
    all_use_cases = fetch_use_cases(conn)
    unreviewed = fetch_by_status(conn, "new")
    unmapped = fetch_unmapped(conn)
    by_theme = fetch_grouped(conn, "themes", "name", "theme_id", "use_case_theme_links", "use_case_id")
    by_wg = fetch_grouped(conn, "working_groups", "slug", "working_group_id", "use_case_working_group_links", "use_case_id")
    candidate_terms = fetch_candidate_taxonomy_terms(conn)

    candidate_terms_table = "".join(
        f"<tr><td>{esc(term)}</td><td>{esc(definition)}</td></tr>" for term, definition in candidate_terms
    ) or '<tr><td colspan="2" class="empty">None.</td></tr>'

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>FG-TIDA Use-Case Register</title>
<style>{CSS}</style>
</head>
<body>
<h1>FG-TIDA Use-Case Register</h1>
<p class="subtitle">Read-only snapshot, rebuilt daily from GitHub Issues + reviewer curation.
Submit a use case via <a href="https://github.com/FG-TIDA/use-cases/issues/new/choose">GitHub Issues</a>.</p>

{render_cards(conn)}

<section>
<h2>All use cases</h2>
{render_full_table(all_use_cases)}
</section>

<section>
<h2>Unreviewed</h2>
{render_use_case_table(unreviewed)}
</section>

<section>
<h2>Unmapped (no theme or working group yet)</h2>
{render_use_case_table(unmapped)}
</section>

<section>
<h2>By theme</h2>
{render_grouped(by_theme)}
</section>

<section>
<h2>By working group</h2>
{render_grouped(by_wg)}
</section>

<section>
<h2>Candidate taxonomy terms</h2>
<table><tr><th>Term</th><th>Definition</th></tr>{candidate_terms_table}</table>
</section>

<section>
<h2>Related use cases</h2>
{render_related(conn)}
</section>

</body>
</html>
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True, help="output HTML path")
    args = parser.parse_args()

    conn = sqlite3.connect(db_path())
    output = build_html(conn)
    conn.close()

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(output)
    print(f"wrote dashboard to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
